### ISSUE TITLE
REPL code window not present

### ISSUE THREAD

**Issue by genevievesuder** [learn-co-curriculum/phase-0-pac-2-switch-statements#4]
### Canvas Link

https://learning.flatironschool.com/courses/6106/pages/selection-with-conditionals-the-switch-statement?module_item_id=471004

### Concern

The repl code window is not displayed in this lesson, or the previous. I am unable to learn about all the coding statements. Only the console window is displayed.

**Comment by jlboba** [comment]
Hello, thank you for raising this issue. 

If you click on the "Show files" button on the replit, you should be able to click on one of the files to see the code. 
However, I agree it should be the default view rather than the console, so I've gone ahead and updated it. 

We apologize for any frustration you might have encountered during this process but thank you for helping us ensure 
that those who follow in your path will not! We appreciate your support 💙
